using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HelloWorld : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        // Вывод в консоль Hello World :D
        print("Hello, World!");
    }

    // Update is called once per frame
    void Update()
    {

    }
}
